### PR TITLE
Added video and audio player instead of URL

### PR DESCRIPTION
**Pull request by OpenSourceSimon**

### CODE REVIEW

**Comment by mikhi32** [comment]
Close the source tag. Thats the bug that make netifly not deploy.

**Comment by OpenSourceSimon** [comment]
> Close the source tag. Thats the bug that make netifly not deploy.

Thanks! I will do that

**Comment by LukaHietala** [comment]
Is this ready to be merged?

**Comment by OpenSourceSimon** [comment]
> Is this ready to be merged?

Yes I think so

**Pull request merged**
